baseURL = "https://copybookjp.me/"
languageCode = "ja"
title = "Copy Book"

enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
canonifyURLs = true
paginate = 75

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[taxonomies]
  tag = 'tags'
  mood = 'mood'
  category = 'categories'

[params]
  description = "Copy book is a collection of texts that are commonly used around the web."
  og_image = "/images/og.jpg"
  sitename = "Copy Book"

[author]
  name = "mu-rayama"
  github = "mu-rayama"
  twitter = "copybookjp"
  dribbble = ""
  behance = ""
